// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/operator-command-center/CommandCenter.tsx": () => import("../components/mockups/operator-command-center/CommandCenter.tsx"),
  "./components/mockups/client-chat/ClientChat.tsx": () => import("../components/mockups/client-chat/ClientChat.tsx")
};
