// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/operator-command-center/CommandCenter.tsx": () => import("../components/mockups/operator-command-center/CommandCenter.tsx"),
  "./components/mockups/one-percent/AccountLibrary.tsx": () => import("../components/mockups/one-percent/AccountLibrary.tsx"),
  "./components/mockups/one-percent/CaseDeliverables.tsx": () => import("../components/mockups/one-percent/CaseDeliverables.tsx"),
  "./components/mockups/one-percent/PaySession.tsx": () => import("../components/mockups/one-percent/PaySession.tsx"),
  "./components/mockups/one-percent/PaymentReview.tsx": () => import("../components/mockups/one-percent/PaymentReview.tsx"),
  "./components/mockups/one-percent/SessionClaim.tsx": () => import("../components/mockups/one-percent/SessionClaim.tsx")
};
